# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/s96abrar/files/DG2D

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/s96abrar/files/DG2D

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s96abrar/files/DG2D/CMakeFiles /home/s96abrar/files/DG2D//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s96abrar/files/DG2D/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dg2d

# Build rule for target.
dg2d: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dg2d
.PHONY : dg2d

# fast build rule for target.
dg2d/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/build
.PHONY : dg2d/fast

Audio/Audio.o: Audio/Audio.cpp.o
.PHONY : Audio/Audio.o

# target to build an object file
Audio/Audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Audio/Audio.cpp.o
.PHONY : Audio/Audio.cpp.o

Audio/Audio.i: Audio/Audio.cpp.i
.PHONY : Audio/Audio.i

# target to preprocess a source file
Audio/Audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Audio/Audio.cpp.i
.PHONY : Audio/Audio.cpp.i

Audio/Audio.s: Audio/Audio.cpp.s
.PHONY : Audio/Audio.s

# target to generate assembly for a file
Audio/Audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Audio/Audio.cpp.s
.PHONY : Audio/Audio.cpp.s

Collision/AABB.o: Collision/AABB.cpp.o
.PHONY : Collision/AABB.o

# target to build an object file
Collision/AABB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Collision/AABB.cpp.o
.PHONY : Collision/AABB.cpp.o

Collision/AABB.i: Collision/AABB.cpp.i
.PHONY : Collision/AABB.i

# target to preprocess a source file
Collision/AABB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Collision/AABB.cpp.i
.PHONY : Collision/AABB.cpp.i

Collision/AABB.s: Collision/AABB.cpp.s
.PHONY : Collision/AABB.s

# target to generate assembly for a file
Collision/AABB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Collision/AABB.cpp.s
.PHONY : Collision/AABB.cpp.s

Draw/Draw.o: Draw/Draw.cpp.o
.PHONY : Draw/Draw.o

# target to build an object file
Draw/Draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Draw/Draw.cpp.o
.PHONY : Draw/Draw.cpp.o

Draw/Draw.i: Draw/Draw.cpp.i
.PHONY : Draw/Draw.i

# target to preprocess a source file
Draw/Draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Draw/Draw.cpp.i
.PHONY : Draw/Draw.cpp.i

Draw/Draw.s: Draw/Draw.cpp.s
.PHONY : Draw/Draw.s

# target to generate assembly for a file
Draw/Draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Draw/Draw.cpp.s
.PHONY : Draw/Draw.cpp.s

Math/FPSutils.o: Math/FPSutils.cpp.o
.PHONY : Math/FPSutils.o

# target to build an object file
Math/FPSutils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Math/FPSutils.cpp.o
.PHONY : Math/FPSutils.cpp.o

Math/FPSutils.i: Math/FPSutils.cpp.i
.PHONY : Math/FPSutils.i

# target to preprocess a source file
Math/FPSutils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Math/FPSutils.cpp.i
.PHONY : Math/FPSutils.cpp.i

Math/FPSutils.s: Math/FPSutils.cpp.s
.PHONY : Math/FPSutils.s

# target to generate assembly for a file
Math/FPSutils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Math/FPSutils.cpp.s
.PHONY : Math/FPSutils.cpp.s

Platform/Platform.o: Platform/Platform.cpp.o
.PHONY : Platform/Platform.o

# target to build an object file
Platform/Platform.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Platform/Platform.cpp.o
.PHONY : Platform/Platform.cpp.o

Platform/Platform.i: Platform/Platform.cpp.i
.PHONY : Platform/Platform.i

# target to preprocess a source file
Platform/Platform.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Platform/Platform.cpp.i
.PHONY : Platform/Platform.cpp.i

Platform/Platform.s: Platform/Platform.cpp.s
.PHONY : Platform/Platform.s

# target to generate assembly for a file
Platform/Platform.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Platform/Platform.cpp.s
.PHONY : Platform/Platform.cpp.s

Textures/Textures.o: Textures/Textures.cpp.o
.PHONY : Textures/Textures.o

# target to build an object file
Textures/Textures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Textures/Textures.cpp.o
.PHONY : Textures/Textures.cpp.o

Textures/Textures.i: Textures/Textures.cpp.i
.PHONY : Textures/Textures.i

# target to preprocess a source file
Textures/Textures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Textures/Textures.cpp.i
.PHONY : Textures/Textures.cpp.i

Textures/Textures.s: Textures/Textures.cpp.s
.PHONY : Textures/Textures.s

# target to generate assembly for a file
Textures/Textures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/Textures/Textures.cpp.s
.PHONY : Textures/Textures.cpp.s

demo/main.o: demo/main.cpp.o
.PHONY : demo/main.o

# target to build an object file
demo/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/demo/main.cpp.o
.PHONY : demo/main.cpp.o

demo/main.i: demo/main.cpp.i
.PHONY : demo/main.i

# target to preprocess a source file
demo/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/demo/main.cpp.i
.PHONY : demo/main.cpp.i

demo/main.s: demo/main.cpp.s
.PHONY : demo/main.s

# target to generate assembly for a file
demo/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/demo/main.cpp.s
.PHONY : demo/main.cpp.s

events/Handle_SDL_events.o: events/Handle_SDL_events.cpp.o
.PHONY : events/Handle_SDL_events.o

# target to build an object file
events/Handle_SDL_events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/events/Handle_SDL_events.cpp.o
.PHONY : events/Handle_SDL_events.cpp.o

events/Handle_SDL_events.i: events/Handle_SDL_events.cpp.i
.PHONY : events/Handle_SDL_events.i

# target to preprocess a source file
events/Handle_SDL_events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/events/Handle_SDL_events.cpp.i
.PHONY : events/Handle_SDL_events.cpp.i

events/Handle_SDL_events.s: events/Handle_SDL_events.cpp.s
.PHONY : events/Handle_SDL_events.s

# target to generate assembly for a file
events/Handle_SDL_events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/events/Handle_SDL_events.cpp.s
.PHONY : events/Handle_SDL_events.cpp.s

globals.o: globals.cpp.o
.PHONY : globals.o

# target to build an object file
globals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/globals.cpp.o
.PHONY : globals.cpp.o

globals.i: globals.cpp.i
.PHONY : globals.i

# target to preprocess a source file
globals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/globals.cpp.i
.PHONY : globals.cpp.i

globals.s: globals.cpp.s
.PHONY : globals.s

# target to generate assembly for a file
globals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/globals.cpp.s
.PHONY : globals.cpp.s

ini/ini.o: ini/ini.cpp.o
.PHONY : ini/ini.o

# target to build an object file
ini/ini.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/ini/ini.cpp.o
.PHONY : ini/ini.cpp.o

ini/ini.i: ini/ini.cpp.i
.PHONY : ini/ini.i

# target to preprocess a source file
ini/ini.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/ini/ini.cpp.i
.PHONY : ini/ini.cpp.i

ini/ini.s: ini/ini.cpp.s
.PHONY : ini/ini.s

# target to generate assembly for a file
ini/ini.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/ini/ini.cpp.s
.PHONY : ini/ini.cpp.s

std/STD.o: std/STD.cpp.o
.PHONY : std/STD.o

# target to build an object file
std/STD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/std/STD.cpp.o
.PHONY : std/STD.cpp.o

std/STD.i: std/STD.cpp.i
.PHONY : std/STD.i

# target to preprocess a source file
std/STD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/std/STD.cpp.i
.PHONY : std/STD.cpp.i

std/STD.s: std/STD.cpp.s
.PHONY : std/STD.s

# target to generate assembly for a file
std/STD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/std/STD.cpp.s
.PHONY : std/STD.cpp.s

ttf/ttf.o: ttf/ttf.cpp.o
.PHONY : ttf/ttf.o

# target to build an object file
ttf/ttf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/ttf/ttf.cpp.o
.PHONY : ttf/ttf.cpp.o

ttf/ttf.i: ttf/ttf.cpp.i
.PHONY : ttf/ttf.i

# target to preprocess a source file
ttf/ttf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/ttf/ttf.cpp.i
.PHONY : ttf/ttf.cpp.i

ttf/ttf.s: ttf/ttf.cpp.s
.PHONY : ttf/ttf.s

# target to generate assembly for a file
ttf/ttf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/ttf/ttf.cpp.s
.PHONY : ttf/ttf.cpp.s

utils/utils.o: utils/utils.cpp.o
.PHONY : utils/utils.o

# target to build an object file
utils/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/utils/utils.cpp.o
.PHONY : utils/utils.cpp.o

utils/utils.i: utils/utils.cpp.i
.PHONY : utils/utils.i

# target to preprocess a source file
utils/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/utils/utils.cpp.i
.PHONY : utils/utils.cpp.i

utils/utils.s: utils/utils.cpp.s
.PHONY : utils/utils.s

# target to generate assembly for a file
utils/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dg2d.dir/build.make CMakeFiles/dg2d.dir/utils/utils.cpp.s
.PHONY : utils/utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dg2d"
	@echo "... Audio/Audio.o"
	@echo "... Audio/Audio.i"
	@echo "... Audio/Audio.s"
	@echo "... Collision/AABB.o"
	@echo "... Collision/AABB.i"
	@echo "... Collision/AABB.s"
	@echo "... Draw/Draw.o"
	@echo "... Draw/Draw.i"
	@echo "... Draw/Draw.s"
	@echo "... Math/FPSutils.o"
	@echo "... Math/FPSutils.i"
	@echo "... Math/FPSutils.s"
	@echo "... Platform/Platform.o"
	@echo "... Platform/Platform.i"
	@echo "... Platform/Platform.s"
	@echo "... Textures/Textures.o"
	@echo "... Textures/Textures.i"
	@echo "... Textures/Textures.s"
	@echo "... demo/main.o"
	@echo "... demo/main.i"
	@echo "... demo/main.s"
	@echo "... events/Handle_SDL_events.o"
	@echo "... events/Handle_SDL_events.i"
	@echo "... events/Handle_SDL_events.s"
	@echo "... globals.o"
	@echo "... globals.i"
	@echo "... globals.s"
	@echo "... ini/ini.o"
	@echo "... ini/ini.i"
	@echo "... ini/ini.s"
	@echo "... std/STD.o"
	@echo "... std/STD.i"
	@echo "... std/STD.s"
	@echo "... ttf/ttf.o"
	@echo "... ttf/ttf.i"
	@echo "... ttf/ttf.s"
	@echo "... utils/utils.o"
	@echo "... utils/utils.i"
	@echo "... utils/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

